version: '3'

services:
  database:
    image: influxdb:alpine
    ports:
      - 8086:8086
      - 2003:2003
    volumes:
      - "./lib/influxdb:/var/lib/influxdb"
    networks:
      - database

  chronograf:
    image: chronograf:1.6-alpine
    ports:
      - 8888:8888
    environment:
        - "INFLUXDB_URL=http://database:8086"
        #command : "--influxdb-url=http://database:8086"
    networks:
      - database
      - default

networks:
  database:
